<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2016-08-08 20:30:33
 */
return [
    'allShared' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'js/all-7d64bde27bafa71bda8d9bdc3119f742.js',
        ],
        'css' => [
            'css/all-b6d1a2eb152424e77f7f004ccb8bea9b.css',
        ],
    ],
    'stock' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'js/all-89da84c39c927b5bbe2dca399b77b731.js',
        ],
        'css' => [
            'css/all-a3be84060e38a80c20167bcd6e12731c.css',
        ],
    ],
    'yii\\web\\JqueryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'allShared',
        ],
    ],
    'yii\\web\\YiiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'allShared',
        ],
    ],
    'app\\assets\\AppAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'allShared',
        ],
    ],
    'app\\assets\\StockAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AppAsset',
            'stock',
        ],
    ],
];